const countryNameToCode = {
    "United States": "US",
    Canada: "CA",
    "United Kingdom": "GB",
    Tunisia: "TN",
    Palestine: "PS",
    "United Arab Emirates": "AE",
    Jordan: "JO",
    Oman: "OM",
    Lebanon: "LB",
    Syria: "SY",
    Qatar: "QA",
    Yemen: "YE",
    Kuwait: "KW",
    Bahrain: "BH",
    "Saudi Arabia": "SA",
    Egypt: "EG",
    Algeria: "DZ",
    Morocco: "MA",
    "Western Sahara": "EH",
    "Mauritania": "MR",
    "Mali": "ML",
};

export default countryNameToCode;